### ISSUE TITLE
Is there a simple way to make overlay for stream?

### ISSUE THREAD

**Issue by AlexanderKozhevin** [juniorxsound/libav-RTMP-Streaming#2]
Everything works as charm, I just wanted to know if I can set up watermark?
Any reference will be helpful 🙏

**Comment by juniorxsound** [comment]
Thanks @AlexanderKozhevin. [Here is an example of how to use a PNG file to watermark a video stream](https://github.com/leixiaohua1020/simplest_ffmpeg_video_filter/blob/master/simplest_ffmpeg_video_filter/simplest_ffmpeg_video_filter.cpp), hope this helps :pray:
