### ISSUE TITLE
Can we stream live desktop screen?

### ISSUE THREAD

**Issue by akshaykatale99** [juniorxsound/libav-RTMP-Streaming#3]
Can we stream the live desktop screen? what can be done to achieve it?

**Comment by gigabyteservice** [comment]
@juniorxsound please guide us how we can record the screen and stream it to any rtmp server

**Comment by juniorxsound** [comment]
Hi @gigabyteservice @akshaykatale99, streaming from a desktop screen would require to use an OS specific input API and is out of scope for this repo. However, here is one example that might be helpful https://github.com/abdullahfarwees/screen-recorder-ffmpeg-cpp
